# INFO-F-422 -  Statistical Foundations of Machine Learning 

### Couchard Darious - __[Darius.Couchard@ulb.be](mailto:Darius.Couchard@ulb.be) - Student ID 425366__
### Donne Stefano - __[Stefano.Donne@ulb.be](mailto:Stefano.Donne@ulb.be) - Student ID 408801__
### Parent Paul - __[Paul.Parent@ulb.be](mailto:Paul.Parent@ulb.be) - Student ID 495257__

## 4) In this section the best model obtained so far is used to predict labels on the test set of the DrivenData competition

In [5]:
library(randomForest)
library(caret)
test_set <- read.csv("../Data/PreProcess/test_data.csv")

In [2]:
load("4-Models/random_forest.RData") # load Random Forest trained model -> name : classifierRF
pred <- predict(classifierRF,test_set, type = "class") # Random Forest model prediction on test sett

In [3]:
output <- data.frame(id=test_set$id,status_group=pred)
output

      id    status_group
1     50785 functional
2     51630 functional
3     17168 functional
4     45559 non functional
5     49871 functional
6     52449 functional
7     24806 functional
8     28965 non functional
9     36301 non functional
10    54122 functional
11      419 functional
12    45750 non functional
13      653 non functional
14    14017 functional
15    44607 functional
16    40228 functional
17    27714 functional
18    28785 functional
19    28330 functional
20    18532 non functional
21    69961 functional
22    55083 functional
23     8691 non functional
24    30331 non functional
25    70970 functional
26    61136 functional
27    28799 non functional
28    46825 non functional
29    44718 functional
30    37350 functional
...   ...   ...
14821 52228 functional
14822 70038 functional
14823 25901 non functional
14824 21131 functional
14825 26580 non functional
14826 66059 non functional
14827 32944 functional
14828 13686 functional
14829  8471 non functional
14830 19620 functional
14831 74162 non functional
14832 37994 functional
14833 71151 functional
14834 45017 functional
14835 12592 functional
14836 58693 functional
14837 57539 functional
14838 71252 non functional
14839  7869 functional
14840 57316 functional
14841 59757 functional
14842 64579 functional
14843 57731 functional needs repair
14844 65541 functional
14845 68174 functional
14846 39307 non functional
14847 18990 functional
14848 28749 functional
14849 33492 functional
14850 68707 non functional

In [9]:
write.csv(output,"../Data/TestOutput/output.csv", row.names=FALSE)